BASE_POS_DEFENCE = [];
BASE_POS_AIR_TRANSPORT_HELI = [];
BASE_POS_AIR_COMBAT_HELI = [];
BASE_POS_AIR_COMBAT_JET = [];
BASE_POS_GROUND_TRANSPORT_VEHICLE = [];
BASE_POS_GROUND_COMBAT_VEHICLE = [];
BASE_POS_GROUND_COMBAT_INFANTRY = [];